### ISSUE TITLE
Outputs of .filter() and .map() are only iterable once

### ISSUE THREAD

**Issue by vishwam** [riteshrao/jsiterable#1]
Repro:
```js
> let Iterable = require('jsiterable').default;
> let i2 = new Iterable(['a', 'b', 'c']);

> let i3 = i2.filter(x => x === 'b');
> i3.items()
[ 'b' ]
> i3.items()
[]

> let i4 = i2.map(x => x + '1');
> i4.items()
[ 'a1', 'b1', 'c1' ]
> i4.items()
[]
```

**Comment by riteshrao** [comment]
Iterable in this library are consumables, meaning that they consume its source and can only be iterated once. If you wish to iterate multiple times use .items() which hydrates as an array which can be iterated over multiple times.

**Comment by riteshrao** [comment]
Valid bug after understanding the scenario. Issue is that the iterable is consuming the source, if the source itself is a iterable whose source is a generator. Since the generator essentially is exhausted, multiple iterations don't work.
